### ISSUE TITLE
No dependency factory available for this dependency type: MultiEntryDependency

### ISSUE THREAD

**Issue by liitfr** [static-dev/spike-pushstate#24]
Hi ! 
Coming from roots I'm discovering spike & today played with it.

```
mathias@mathias-Inspiron-7559:~/dev_web/testspike/p3$ spike new test
mathias@mathias-Inspiron-7559:~/dev_web/testspike/p3/test$ npm install spike -S
mathias@mathias-Inspiron-7559:~/dev_web/testspike/p3/test$ npm install spike-pushstate -S
```

As defined in documentation, I installed spike locally alongside spike-pushstate. I get following package.json :

```
{
  "name": "test",
  "description": "test",
  "version": "0.0.1",
  "author": "",
  "ava": {
    "verbose": "true"
  },
  "bugs": "https://github.com//test/issues",
  "dependencies": {
    "babel-preset-latest": "^6.16.0",
    "hard-source-webpack-plugin": "0.2.2",
    "reshape-standard": "^0.4.2",
    "spike": "^0.13.0",
    "spike-css-standards": "^0.1.3",
    "spike-page-id": "^0.1.0",
    "spike-pushstate": "^0.2.0",
    "webpack": "^1.13.3"
  },
  "devDependencies": {
    "ava": "^0.17.0",
    "rimraf": "^2.5.4",
    "snazzy": "^5.0.0",
    "spike-core": "^0.12.3",
    "standard": "^8.6.0"
  },
  "homepage": "https://github.com//test",
  "main": "app.js",
  "private": true,
  "repository": "https://github.com//test",
  "scripts": {
    "lint": "standard | snazzy",
    "precommit": "npm run lint -s",
    "pretest": "npm run lint -s",
    "test": "NODE_ENV=test ava"
  }
}
```

Then modified app.js : 

```
const path = require('path')
const HardSourcePlugin = require('hard-source-webpack-plugin')
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('babel-preset-latest')
const pageId = require('spike-page-id')
const PushState = require('spike-pushstate')

module.exports = {
  devtool: 'source-map',
  matchers: {
    html: '*(**/)*.sgr',
    css: '*(**/)*.sss'
  },
  ignore: ['**/layout.sgr', '**/_*', '**/.*', '_cache/**', 'readme.md'],
  reshape: (ctx) => {
    return htmlStandards({
      webpack: ctx,
      locals: { pageId: pageId(ctx), foo: 'bar' }
    })
  },
  postcss: (ctx) => {
    return cssStandards({ webpack: ctx })
  },
  babel: { presets: [jsStandards] },
  plugins: [
    new PushState(),
    new HardSourcePlugin({
      environmentPaths: { root: __dirname },
      recordsPath: path.join(__dirname, '_cache/records.json'),
      cacheDirectory: path.join(__dirname, '_cache/hard_source_cache')
    })
  ]
}
```

I get following error when trying to execute spike compile : 

```
mathias@mathias-Inspiron-7559:~/dev_web/testspike/p3/test$ spike compile
✗ ERROR
Error: Error: No dependency factory available for this dependency type: MultiEntryDependency
    at Spike.compileCallback (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/index.js:168:31)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:174:20)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:395:18)
    at /usr/local/lib/node_modules/spike/node_modules/tapable/lib/Tapable.js:99:11
    at tryCatchReject (/home/mathias/dev_web/testspike/p3/test/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/mathias/dev_web/testspike/p3/test/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/home/mathias/dev_web/testspike/p3/test/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/home/mathias/dev_web/testspike/p3/test/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/mathias/dev_web/testspike/p3/test/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/mathias/dev_web/testspike/p3/test/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
mathias@mathias-Inspiron-7559:~/dev_web/testspike/p3/test$ ^C
mathias@mathias-Inspiron-7559:~/dev_web/testspike/p3/test$ 

```

Maybe I did something wrong ? but I tried to do as detailled in documentation.
I will be pleased to help & answer your questions if any.

Mat

**Comment by jescalan** [comment]
So spike pushstate needs to be run with a local version of spike rather than global due to a webpack bug that unfortunately will not be fixed. I should have added a caveat about this to the readme though, let me add this right now.

Also, this plugin might not be working with the latest version of spike, I'll check it over and see if I can get it patched today. This was an early experiment, but spike has come a long way since and I suspect some of the API changes might have broken its compatibility.

Sorry this wasn't more clear in the readme, entirely my fault!

**Comment by jescalan** [comment]
Ah actually it was in the readme in the install instructions. I just clarified it a little though 😁

**Comment by jescalan** [comment]
Ok, just tested it with a fresh project and it's working. Whoo! See updated readme for caveats and updates. Basically:

- Run `npm i spike -S` to install spike locally
- Add to the `scripts` section in `package.json`: `watch: 'spike watch'`
- Remove `sourcemap` option from `app.js`
- In your main `index.js` file, add `require('spike-pushstate')`
- Use `npm run watch` to initialize

Then you should be good to go!

**Comment by liitfr** [comment]
Thanks Jeff ! 
Actually I installed spike locally as explained in readme,
but didn't think about the `watch: 'spike watch'` trick

learned something new today ;)
